name: CI/CD Pipeline

on:
  push:
    branches:
      - vercel-deployment # Update to the branch you're working on
  pull_request:
    branches:
      - vercel-deployment # Ensure pull requests also run this workflow

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Update to Node.js 20.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # This will automatically use Node.js 20.x

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Use Node.js 20.x instead of older versions
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js dependencies
        uses: actions/cache@v3 # Still compatible with Node.js 20.x
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}

      - name: Install dependencies (frontend)
        working-directory: ./frontend
        run: npm install

      - name: Install dependencies (backend)
        working-directory: ./backend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Test frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Build backend
        working-directory: ./backend
        run: npm run build # Add a build command if necessary, or replace with start command

      - name: Run backend tests
        working-directory: ./backend
        run: npm test # Add a test script in your backend's package.json


      # Optional: Deployment steps (e.g., to Vercel or other platforms)
