name: integration

on:
  push:
    branches:
      - testing-login
      - main
      - Next-development
      - Jam
      - JamesDev
      - DWJ
      - development
      - KishanDev
      - MaseTheStudent-patch-1
      - anson
      - main2
      - vercel-deployment
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [20.14.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Backend Steps
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Set up environment variables
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

      # Concurrently run backend and frontend builds
      - name: Run backend and frontend concurrently
        run: |
          npm install concurrently --save-dev
          concurrently "npm run start-ci --prefix backend" "npm run build --prefix frontend"
