name: MNNN Stack CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: > 
          --health-cmd "echo 'db.runCommand({ping:1})' | mongosh" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up environment variables
        run: |
          echo "MONGODB_URI=mongodb://localhost:27017/mydatabase" >> .env

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build Next.js project
        run: |
          cd nextjs-app
          npm run build

      - name: Build Nest.js project
        run: |
          cd nestjs-app
          npm run build

      - name: Run tests for Next.js
        run: |
          cd nextjs-app
          npm run test

      - name: Run tests for Nest.js
        run: |
          cd nestjs-app
          npm run test

      - name: MongoDB tests
        run: |
          npm run test:mongo

      - name: Build for production
        run: npm run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Deploy to production (optional)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: npm run deploy
